use Medicare_System

INSERT INTO MEDICAL_CREDENTIALS (Clinician_enrollment_id, Credentials, MEDICAL_SCHOOL, Graduation_Year, Primary_Specialty, Secondary_Specialist1, Secondary_Specialist2, Secondary_Specialist3, Secondary_Specialist4, All_Secondary_Specialty)
VALUES
('10224738', 'CP', 'UNIVERSITY OF SOUTH ALABAMA COLLEGE OF MEDICINE', 2012, 'FAMILY MEDICINE', NULL, NULL, NULL, NULL, NULL),
('10224739', 'MD', 'OHIO UNIVERSITY, COLLEGE OF OSTEOPATHIC MEDICINE', 2000, 'FAMILY MEDICINE', NULL, NULL, NULL, NULL, NULL),
('11646166', 'CP', 'UNIVERSITY OF SOUTH ALABAMA COLLEGE OF MEDICINE', 2018, 'NURSE PRACTITIONER', NULL, NULL, NULL, NULL, NULL),
('10224740', 'MD', 'JEFFERSON MEDICAL COLLEGE OF THOMAS JEFFERSON UNIVERSITY', 1983, 'GENERAL PRACTICE', 'EMERGENCY MEDICINE', NULL, 'EMERGENCY MEDICINE', NULL, NULL),
('10224741', 'CP', 'UNIVERSITY OF SOUTH ALABAMA COLLEGE OF MEDICINE', 2018, 'NURSE PRACTITIONER', NULL, NULL, NULL, NULL, NULL),
('10224742', 'CP', 'HAHNEMAN MEDICAL COLLEGE OF THE PACIFIC', 1984, 'INTERNAL MEDICINE', NULL, NULL, NULL, NULL, NULL),
('10224743', 'MD', 'HAHNEMAN MEDICAL COLLEGE OF THE PACIFIC', 1984, 'INTERNAL MEDICINE', NULL, NULL, NULL, NULL, NULL),
('10224744', 'DC', 'UNIVERSITY OF MISSOURI, COLUMBIA SCHOOL OF MEDICINE', 1995, 'EMERGENCY MEDICINE', 'PHYSICAL MEDICINE AND REHABILITATION', NULL, 'PHYSICAL MEDICINE AND REHABILITATION', NULL, NULL),
('10224745', 'CP', 'DUKE UNIVERSITY SCHOOL OF MEDICINE', 1985, 'FAMILY MEDICINE', NULL, NULL, NULL, NULL, NULL),
('11645836', 'DC', 'DUKE UNIVERSITY SCHOOL OF MEDICINE', 1985, 'FAMILY MEDICINE', NULL, NULL, NULL, NULL, NULL),
('10224746', 'CSW', 'UNIVERSITY OF SOUTH ALABAMA COLLEGE OF MEDICINE', 2010, 'PHYSICIAN ASSISTANT', NULL, NULL, NULL, NULL, NULL),
('10224749', 'MD', 'UNIVERSITY OF SOUTH ALABAMA COLLEGE OF MEDICINE', 2010, 'PHYSICIAN ASSISTANT', NULL, NULL, NULL, NULL, NULL),
('10224750', 'MD', 'UNIVERSITY OF SOUTH ALABAMA COLLEGE OF MEDICINE', 2018, 'NURSE PRACTITIONER', NULL, NULL, NULL, NULL, NULL),
('10224751', 'MD', 'UNIVERSITY OF SOUTH ALABAMA COLLEGE OF MEDICINE', 1996, 'PHYSICAL THERAPY', NULL, NULL, NULL, NULL, NULL),
('10224752', 'CP', 'UNIVERSITY OF SOUTH ALABAMA COLLEGE OF MEDICINE', 2015, 'PHYSICAL THERAPY', NULL, NULL, NULL, NULL, NULL),
('10224753', 'MD', 'DUKE UNIVERSITY SCHOOL OF MEDICINE', 1976, 'OPHTHALMOLOGY', NULL, NULL, NULL, NULL, NULL),
('10224754', 'CP', 'NEW YORK MEDICAL COLLEGE', 1975, 'OPHTHALMOLOGY', NULL, NULL, NULL, NULL, NULL),
('10224756', 'MD', 'NEW YORK MEDICAL COLLEGE', 2011, 'OPHTHALMOLOGY', NULL, NULL, NULL, NULL, NULL),
('10224757', 'DC', 'UNIVERSITY OF CALIFORNIA, DAVIS SCHOOL OF MEDICINE', 1989, 'DERMATOLOGY', NULL, NULL, NULL, NULL, NULL),
('10224758', 'CSW', 'COLUMBIA UNIVERSITY COLLEGE OF PHYSICIANS AND SURGEONS', 2000, 'DERMATOLOGY', NULL, NULL, NULL, NULL, NULL);
